# Generated by Django 2.2.6 on 2020-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='webhook',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
